# Site settings
title: Andry Supian
email: your-email@domain.com
url: https://andry.me
description: "Product Manager & Data Engineer. Passionate about user-driven, data-verified design."
skills: "Product Manager & Data Engineer.
Passionate about user-driven, data-verified design."
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fff
  primary-rgb: "112,123,123"
  secondary: 808080
  maintext: 808080
  maintextlite: b2b2b2
  maintextaccent: 3b9886

# Footer settings
footer:
  copyright: Andry Supian

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/andrysupian
  - title: github
    url: http://github.com/asupian
  - title: linkedin
    url: https://www.linkedin.com/in/andrysupian/

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
